# Dockerfile dla VirtualGardener.Server

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migration
WORKDIR /app
COPY --from=build /publish .
COPY . ./
RUN dotnet tool restore # Przywracanie narzędzi lokalnych
ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "/app/VirtualGardener.Server.csproj"]

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["dotnet", "VirtualGardener.Server.dll"]
